// Copyright YoungSterYSD. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace FDGameplayTags
{
	// 角色属性
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Attack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Defense);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Health);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_HealthMax);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Healing);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_CritRate);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_CritDamage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_AttackSpeed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_CastSpeed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_DamageIncrease);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_DamageDecrease);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_BodyStrength);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Tenacity);

	// 输入
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability2);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability3);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability4);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Camera_Zoom);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ClickMove);

	// 初始化状态
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	// 角色状态
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Dodging);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Parrying);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_MovementLocked);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Animation_Playing);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Animation_UpperBody);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Recovery);

	// 游戏事件
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);

	// 动态数值传入
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);

	// 消息通道
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Experience_Loaded);

	// 移动模式
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Grounded);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_InAir);

	// 角色状态 (CharState)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(CharState_Idle);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(CharState_Walk);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(CharState_Run);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(CharState_Sprint);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(CharState_InBattle);

	// 移动方向 (八方向)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MoveDirection_F_0);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MoveDirection_F_L_45);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MoveDirection_F_R_45);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MoveDirection_L_90);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MoveDirection_R_90);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MoveDirection_B_180);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MoveDirection_B_L_45);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MoveDirection_B_R_45);

	// 动画阶段
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AnimPhase_Start);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AnimPhase_Loop);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AnimPhase_Stop);
}
